/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2023.07                                                     */
/* Component Version:  V2023.07                                                     */
/* CAS Version:        V.04.00M0P07172023                                           */
/* SAS Version:        V.04.00M0P071723                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       fbecbba9-8e44-48f2-a2c1-fb25a2d66ce7                         */
/* Node GUID:          f47d8a74-9fb8-435d-a48c-3706c0345220                         */
/* Node Id:            EH2UOJ4CUQFHZTDBN8GC66TR4                                    */
/* Algorithm:          Gradient Boosting                                            */
/* Generated by:       sorowl                                                       */
/* Date:               16AUG2023:14:07:25                                           */
/*----------------------------------------------------------------------------------*/
package MS_f47d8a749fb8435da48c3706c0345220_16AUG2023140725094 / overwrite=yes;
   dcl package score _EH2UOJ4CUQFHZTDBN8GC66TR4();
   dcl double EM_EVENTPROBABILITY;
   dcl double "CLAGE";
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double "CLNO";
   dcl double EM_PROBABILITY;
   dcl double "DEBTINC";
   dcl double "LOAN";
   dcl double "MORTDUE";
   dcl double "VALUE";
   dcl double "YOJ";
   dcl nchar(7) "REASON";
   dcl double "DELINQ";
   dcl double "DEROG";
   dcl nchar(7) "JOB";
   dcl double "NINQ";
   dcl double "P_BAD1" having label n'Predicted: BAD=1';
   dcl double "P_BAD0" having label n'Predicted: BAD=0';
   dcl nchar(12) "I_BAD" having label n'Into: BAD';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   varlist allvars [_all_];
 
    
   method init();
      _EH2UOJ4CUQFHZTDBN8GC66TR4.setvars(allvars);
      _EH2UOJ4CUQFHZTDBN8GC66TR4.setkey(n'3BC83821DC51C15351923DE50043F841F06B3F42');
   end;
    
   method post_EH2UOJ4CUQFHZTDBN8GC66TR4();
      dcl double _P_;
       
      if "P_BAD0" = . then "P_BAD0" = 0.8005033557;
      if "P_BAD1" = . then "P_BAD1" = 0.1994966443;
      if MISSING("I_BAD") then do ;
      _P_ = 0.0;
      if "P_BAD1" > _P_ then do ;
      _P_ = "P_BAD1";
      "I_BAD" = '           1';
      end;
      if "P_BAD0" > _P_ then do ;
      _P_ = "P_BAD0";
      "I_BAD" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_BAD1";
      EM_CLASSIFICATION = "I_BAD";
      EM_PROBABILITY = MAX("P_BAD0", "P_BAD1");
    
   end;
    
 
   method score(
      double "CLAGE",
      double "CLNO",
      double "DEBTINC",
      double "DELINQ",
      double "DEROG",
      char(7) "JOB",
      double "LOAN",
      double "MORTDUE",
      double "NINQ",
      char(7) "REASON",
      double "VALUE",
      double "YOJ",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(12) "I_BAD",
      IN_OUT double "P_BAD0",
      IN_OUT double "P_BAD1",
      IN_OUT double "_P_",
      IN_OUT char(4) "_WARN_"
   );
      this."CLAGE"= "CLAGE";
      this."CLNO"= "CLNO";
      this."DEBTINC"= "DEBTINC";
      this."DELINQ"= "DELINQ";
      this."DEROG"= "DEROG";
      this."JOB"= "JOB";
      this."LOAN"= "LOAN";
      this."MORTDUE"= "MORTDUE";
      this."NINQ"= "NINQ";
      this."REASON"= "REASON";
      this."VALUE"= "VALUE";
      this."YOJ"= "YOJ";
 
      _EH2UOJ4CUQFHZTDBN8GC66TR4.scoreRecord();
      post_EH2UOJ4CUQFHZTDBN8GC66TR4();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_BAD"= this."I_BAD";
      "P_BAD0"= this."P_BAD0";
      "P_BAD1"= this."P_BAD1";
      "_P_"= this."_P_";
      "_WARN_"= this."_WARN_";
   end;
 
 
   method predictedscore(
      double "CLAGE",
      double "CLNO",
      double "DEBTINC",
      double "DELINQ",
      double "DEROG",
      char(7) "JOB",
      double "LOAN",
      double "MORTDUE",
      double "NINQ",
      char(7) "REASON",
      double "VALUE",
      double "YOJ",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(12) "I_BAD",
      IN_OUT double "P_BAD0",
      IN_OUT double "P_BAD1",
      IN_OUT char(4) "_WARN_"
   );
      this."CLAGE"= "CLAGE";
      this."CLNO"= "CLNO";
      this."DEBTINC"= "DEBTINC";
      this."DELINQ"= "DELINQ";
      this."DEROG"= "DEROG";
      this."JOB"= "JOB";
      this."LOAN"= "LOAN";
      this."MORTDUE"= "MORTDUE";
      this."NINQ"= "NINQ";
      this."REASON"= "REASON";
      this."VALUE"= "VALUE";
      this."YOJ"= "YOJ";
 
      _EH2UOJ4CUQFHZTDBN8GC66TR4.scoreRecord();
      post_EH2UOJ4CUQFHZTDBN8GC66TR4();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_BAD"= this."I_BAD";
      "P_BAD0"= this."P_BAD0";
      "P_BAD1"= this."P_BAD1";
      "_WARN_"= this."_WARN_";
   end;
 
endpackage;
